baseurl = "https://consolas.tole.es"
title = "Últimas ofertas en consolas y gaming"
theme = "portfolio"
languageCode = "es-es"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
paginate = 30
# disableKinds = ["RSS"]
enableRobotsTXT = true

[sitemap]
  changefreq = "hourly"
  filename = "sitemap.xml"
  priority = 0.5

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "sea"
  description = "Tus productos de gaming al mejor precio"
  copyright = ""
  sidebarAbout = []
  # Enable Google Analytics by entering your tracking code
  gtag="G-1BKKRPRJ18"
  yandex = "c18f9bd7c16058ed"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Raíz  "
  url = "/"
  home = true


  [outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
